import { defineStore } from 'pinia';
import { ref, computed } from 'vue';
import type { WorkspaceAgentSession } from '../services/fileService';
import { createFileServiceClient } from '../services/fileService';

/**
 * 会话管理 store —— 管理多个 Agent 会话的标签页状态(仅元数据)。
 *
 * 重构后(2026-06 memory module):
 * - 不再持有 useAgent() 实例(useAgent 已无状态)
 * - 不再缓存消息到 localStorage(后端 SessionMemory 是唯一真源)
 * - 前端只负责元数据列表 + 切换 + 重命名 + 拉取展示数据
 * - 所有 saveSession/deleteSession 都直接走后端
 */

function isCJK(c: string): boolean {
  const code = c.charCodeAt(0);
  return (code >= 0x4e00 && code <= 0x9fff) || (code >= 0x3400 && code <= 0x4dbf);
}

function generateSessionName(text: string): string {
  const maxUnits = 20;
  let units = 0;
  let i = 0;
  for (i = 0; i < text.length; i++) {
    const char = text[i];
    if (char === '\n') break;
    units += isCJK(char) ? 2 : 1;
    if (units > maxUnits) break;
  }
  const name = text.slice(0, i).trim();
  if (!name) return '';
  return name.length < text.trim().length ? name + '...' : name;
}

export const useSessionStore = defineStore('sessions', () => {
  const sessions = ref<WorkspaceAgentSession[]>([]);
  const activeSessionId = ref<string | null>(null);
  const boundWorkspaceId = ref<string | null>(null);

  // --- Computed ---
  const activeSession = computed<WorkspaceAgentSession | null>(
    () => sessions.value.find(s => s.id === activeSessionId.value) ?? null
  );

  // --- Methods ---

  /** 绑定到指定工作区:从后端拉取 session 列表 */
  async function bindWorkspace(workspaceId: string | null, agentSessions?: WorkspaceAgentSession[]) {
    boundWorkspaceId.value = workspaceId;

    if (!workspaceId) {
      sessions.value = [];
      activeSessionId.value = null;
      return;
    }

    if (agentSessions && agentSessions.length > 0) {
      sessions.value = agentSessions;
      activeSessionId.value = sessions.value[0]!.id;
    } else {
      // 工作区无持久化会话:列表置空,不自动创建
      // (前端 UI 在用户发首条消息时会触发创建)
      sessions.value = [];
      activeSessionId.value = null;
    }
  }

  /** 创建新会话 —— 插入到数组最左侧;若已绑定工作区,通知后端持久化 */
  async function createSession(): Promise<WorkspaceAgentSession> {
    const id = `session_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
    const now = Date.now();
    const session: WorkspaceAgentSession = {
      id,
      name: '新会话',
      nameAutoGenerated: false,
      createdAt: now,
    };
    sessions.value.unshift(session);
    activeSessionId.value = id;

    // 通知后端新建 session(后端 WorkspaceManager 会落盘)
    if (boundWorkspaceId.value) {
      try {
        const client = createFileServiceClient();
        await client.saveWorkspaceSession(boundWorkspaceId.value, session);
      } catch (e: any) {
        // 后端 save 失败不阻塞前端 UI;memory 在首条对话流 done 时会重新落盘
        console.warn(`createSession: backend save failed: ${e.message}`);
      }
    }
    return session;
  }

  /** 关闭会话 —— 从后端删除 */
  async function closeSession(id: string) {
    const idx = sessions.value.findIndex(s => s.id === id);
    if (idx === -1) return;
    sessions.value.splice(idx, 1);

    if (boundWorkspaceId.value) {
      try {
        const client = createFileServiceClient();
        await client.deleteWorkspaceSession(boundWorkspaceId.value, id);
      } catch (e: any) {
        console.warn(`closeSession: backend delete failed: ${e.message}`);
      }
    }

    if (activeSessionId.value === id) {
      if (sessions.value.length > 0) {
        const nextIdx = Math.min(idx, sessions.value.length - 1);
        activeSessionId.value = sessions.value[nextIdx]!.id;
      } else {
        activeSessionId.value = null;
      }
    }
  }

  /** 切换活跃会话 */
  function setActiveSession(id: string) {
    if (sessions.value.find(s => s.id === id)) {
      activeSessionId.value = id;
    }
  }

  /** 手动更新会话名称(同步到后端) */
  async function updateSessionName(id: string, name: string) {
    const session = sessions.value.find(s => s.id === id);
    if (!session) return;
    session.name = name;
    session.nameAutoGenerated = false;
    if (boundWorkspaceId.value) {
      try {
        const client = createFileServiceClient();
        await client.saveWorkspaceSession(boundWorkspaceId.value, session);
      } catch (e: any) {
        console.warn(`updateSessionName: backend save failed: ${e.message}`);
      }
    }
  }

  /** 从首条用户消息自动生成会话名称 —— 仅在尚未自动命名时生效 */
  async function autoNameFromFirstMessage(sessionId: string, message: string) {
    const session = sessions.value.find(s => s.id === sessionId);
    if (!session || session.nameAutoGenerated) return;
    const name = generateSessionName(message);
    if (!name) return;
    session.name = name;
    session.nameAutoGenerated = true;
    if (boundWorkspaceId.value) {
      try {
        const client = createFileServiceClient();
        await client.saveWorkspaceSession(boundWorkspaceId.value, session);
      } catch (e: any) {
        console.warn(`autoNameFromFirstMessage: backend save failed: ${e.message}`);
      }
    }
  }

  return {
    sessions,
    activeSessionId,
    activeSession,
    boundWorkspaceId,
    bindWorkspace,
    createSession,
    closeSession,
    setActiveSession,
    updateSessionName,
    autoNameFromFirstMessage,
  };
});
