<template>
  <div class="agent-panel">
    <!-- 会话标签栏 -->
    <AgentSessionTabs
      :sessions="sessionStore.sessions"
      :activeSessionId="sessionStore.activeSessionId"
      :visible="!!(editorStore.activeWorkspaceId || providerSettings.providers.value.length > 0)"
      @update:activeSessionId="sessionStore.setActiveSession($event)"
      @close="sessionStore.closeSession($event)"
      @add="createNewSession"
    />

    <!-- 思考进度条 —— 处理时在面板最上方滚动 -->
    <div v-if="agentCtrl.isProcessing.value" class="thinking-progress">
      <div class="thinking-progress-bar"></div>
    </div>

    <!-- 无提供商时的引导页面 -->
    <AgentGuidePages
      v-if="providerSettings.providers.value.length === 0 || (!editorStore.activeWorkspaceId && editorStore.workspaceRoots.length === 0) || !sessionStore.activeSessionId"
      :hasProviders="providerSettings.providers.value.length > 0"
      :hasWorkspace="!!editorStore.activeWorkspaceId || editorStore.workspaceRoots.length > 0"
      :hasSession="!!sessionStore.activeSessionId"
      @open-settings="$emit('open-settings')"
      @create-session="createNewSession"
    />

    <!-- 有提供商且有活跃会话时显示正常的聊天界面 -->
    <template v-else>
      <AgentMessageList
        ref="messageListRef"
        :messages="visibleMessages"
      />

      <AgentInputArea
        v-model="input"
        :isProcessing="agentCtrl.isProcessing.value"
        @send="send"
        @stop="stopStream"
      />

      <AgentFooter
        :providers="providerSettings.providers.value"
        :activeProviderId="providerSettings.activeId.value"
        :currentMode="currentMode"
        @select-provider="providerSettings.setActive($event)"
        @update:currentMode="agentCtrl.config.value.mode = $event"
        @open-settings="$emit('open-settings')"
      />
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, nextTick, watch } from 'vue';
import { useSessionStore } from '../../stores/sessions';
import { useLLMSettings } from '../../composables/useLLMSettings';
import { useEditorStore } from '../../stores/editor';
import { useAgent } from '../../composables/useAgent';
import { useSessionMessages } from '../../composables/useSessionMessages';
import type { DisplayMessage } from '@openwork/agent';
import AgentSessionTabs from './AgentSessionTabs.vue';
import AgentGuidePages from './AgentGuidePages.vue';
import AgentMessageList from './AgentMessageList.vue';
import AgentInputArea from './AgentInputArea.vue';
import AgentFooter from './AgentFooter.vue';
import { webAgentLog } from '../../services/logger';

defineEmits<{
  'open-settings': [];
}>();

const sessionStore = useSessionStore();
const providerSettings = useLLMSettings();
const editorStore = useEditorStore();
const input = ref('');

// 使用当前活跃 sessionId 驱动 useAgent(无状态,sessionId 在 streamMessage 时再传)
const agentCtrl = useAgent();

// 从后端拉取展示消息(监听 workspaceId / sessionId 变化自动 refresh)
const { messages: persistedMessages, refresh: refreshMessages } = useSessionMessages(
  () => editorStore.activeWorkspaceId,
  () => sessionStore.activeSessionId,
  () => editorStore.workspaceRoot,
);

// 最终展示列表:已落盘消息 + 当前 pending + live 消息(流式期间)
const pendingUserMessage = ref<DisplayMessage | null>(null);
const visibleMessages = computed<DisplayMessage[]>(() => {
  const result = [...persistedMessages.value];
  if (agentCtrl.liveMessage.value) {
    if (pendingUserMessage.value) result.push(pendingUserMessage.value);
    result.push(agentCtrl.liveMessage.value);
  }
  return result;
});

// 切换 session 时清空 pending 和 live
watch(() => sessionStore.activeSessionId, () => {
  pendingUserMessage.value = null;
  agentCtrl.clearLive();
});

const currentMode = computed({
  get: () => agentCtrl.config.value.mode,
  set: (val) => { agentCtrl.config.value.mode = val; },
});

async function createNewSession() {
  await sessionStore.createSession();
}

// 消息列表引用,用于流式期间触发滚动
const messageListRef = ref<InstanceType<typeof AgentMessageList>>();

async function send() {
  if (!sessionStore.activeSessionId) {
    await sessionStore.createSession();
  }
  const sessionId = sessionStore.activeSessionId;
  if (!sessionId) return;

  const text = input.value.trim();
  if (!text) return;
  input.value = '';

  // 插入 pending 用户消息(立即显示,不等 refresh)
  const tempUserMsg: DisplayMessage = {
    id: `pending_user_${Date.now()}`,
    role: 'user',
    content: text,
    timestamp: Date.now(),
    blocks: [{ id: `pending_user_${Date.now()}_r`, type: 'response', content: text }],
  };
  pendingUserMessage.value = tempUserMsg;

  // 自动从首条消息命名会话
  if (sessionStore.activeSession && !sessionStore.activeSession.nameAutoGenerated) {
    sessionStore.autoNameFromFirstMessage(sessionStore.activeSession.id, text);
  }

  const activeFilePath = editorStore.activeTab?.path;
  webAgentLog.info('send: starting streamMessage');

  const streamPromise = agentCtrl.streamMessage(
    sessionId,
    text,
    providerSettings.activeProvider.value,
    activeFilePath,
    {
      onChunk: () => messageListRef.value?.scheduleScroll(false),
      onDone: async () => {
        webAgentLog.info('send: streamMessage completed, refreshing from backend');
        await refreshMessages();
        pendingUserMessage.value = null;
        agentCtrl.clearLive();
        messageListRef.value?.scheduleScroll(true);
      },
      onError: (err) => {
        webAgentLog.error(`send: streamMessage failed: ${err.message}`, { name: err.name, message: err.message });
      },
    },
  );

  await nextTick();
  messageListRef.value?.scrollToBottom();

  try {
    await streamPromise;
  } catch (e: any) {
    webAgentLog.error(`send: streamPromise rejected: ${e.message}`, { name: e.name, message: e.message });
  }
}

function stopStream() {
  agentCtrl.cancelStream();
}
</script>

<style scoped>
.agent-panel {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: var(--bg-secondary);
  position: relative;
  overflow: hidden;
}

/* ===== 思考进度条 ===== */
.thinking-progress {
  position: absolute;
  top: 32px;
  left: 0;
  right: 0;
  height: 3px;
  z-index: 10;
  overflow: hidden;
  background: transparent;
}

.thinking-progress-bar {
  width: 40%;
  height: 100%;
  background: linear-gradient(90deg, transparent, var(--accent-color), transparent);
  animation: progress-scroll 1.2s ease-in-out infinite;
  border-radius: 2px;
}

@keyframes progress-scroll {
  0% {
    transform: translateX(-100%);
  }
  100% {
    transform: translateX(350%);
  }
}
</style>
